base_url = "https://thyraen-robotics.github.io/"
title = "Thyraen Robotics"
description = "Mission-centric autonomy for contested and degraded environments. Autonomous systems that turn commander's intent into coordinated operational effects."
author = "Thyraen Robotics"

compile_sass = false
build_search_index = false

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
debug = false
